// Prebuild script: fetches templates from grabaprompt.com and writes a TypeScript file
// Usage: tsx scripts/pull-templates.ts

import { writeFileSync, mkdirSync } from "fs";
import { join } from "path";

const TEMPLATES_URL = process.env.TEMPLATES_URL || "https://grabaprompt.com/templates.json";
const OUTPUT_PATH = join(__dirname, "..", "src", "data", "templates.ts");

async function main() {
	console.log(`Fetching templates from ${TEMPLATES_URL}...`);

	const response = await fetch(TEMPLATES_URL);
	if (!response.ok) {
		throw new Error(`Failed to fetch templates: ${response.status} ${response.statusText}`);
	}

	const templates = await response.json();
	console.log(`Fetched ${templates.length} templates`);

	const output = `// Auto-generated by scripts/pull-templates.ts — do not edit manually
import type { Template } from "../types";

export const templates: Template[] = ${JSON.stringify(templates, null, "\t")};
`;

	mkdirSync(join(__dirname, "..", "src", "data"), { recursive: true });
	writeFileSync(OUTPUT_PATH, output, "utf-8");
	console.log(`Wrote ${OUTPUT_PATH}`);
}

main().catch((err) => {
	console.error(err);
	process.exit(1);
});
